### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by onmyway133** [getsentry/raven-swift#29]
Hi, I'm curious to see if there is changelog from 0.4.0 to 0.5.0 ?

**Comment by asbjornu** [comment]
@onmyway133 [It is stated in the release](https://github.com/getsentry/raven-swift/releases/tag/0.5.0): 
> Remove warnings

**Comment by asbjornu** [comment]
@onmyway133 I don't disagree with that, but neither me nor @timorzadir are hired by @getsentry; we're only contributing our free time to the project. But since the creation of the competing [sentry-swift](/getsentry/sentry-swift) library, our interest in contributing has sunk quite significantly, to be honest.

**Comment by onmyway133** [comment]
@asbjornu ah I see. You've done a great job actually. We use it in our project 👍
